create table if not exists public.strategy_signals (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  strategy_id text not null references public.strategy_registry(strategy_id) on delete cascade,
  symbol text not null default 'XAUUSD',
  direction text not null check (direction in ('BUY','SELL')),
  state text not null default 'SIGNAL',
  signal_time timestamptz not null,
  broker_time text,
  entry_price numeric,
  stop_price numeric,
  target1_price numeric,
  target2_price numeric,
  score numeric,
  vcpr_pivot numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists strategy_signals_strategy_time_idx
  on public.strategy_signals(strategy_id, signal_time desc);

alter table public.strategy_signals enable row level security;

drop policy if exists "Public can read strategy signals" on public.strategy_signals;
create policy "Public can read strategy signals"
  on public.strategy_signals for select using (true);

insert into public.strategy_registry (
  strategy_id,name,strategy_group,timeframe,status,mode,enabled,dashboard_visible,telegram_enabled,description,rules,evidence
) values (
  'INTRADAY_MTF_V1',
  'XAUUSD Multi-Timeframe Trend Pullback V1',
  'INTRADAY_MTF',
  'M5/M15/H1/H4',
  'FORWARD_TEST',
  'PAPER',
  true,true,true,
  'Paper-test engine combining H4/H1 trend structure, M15 pullback context, M5 confirmation and the permanent VCPR map. No live order execution.',
  jsonb_build_object(
    'h4_regime','Close vs EMA99/SMA200; SMA44 vs EMA99 with SMA44 slope',
    'h1_confirmation','Close vs EMA99; SMA20 vs SMA44 with SMA44 slope',
    'm15_setup','Pullback/touch near SMA20 or SMA44 within ATR-normalized tolerance; VCPR can add support/resistance confluence',
    'm5_trigger','SMA9/SMA20 reclaim or loss plus previous-bar structure break and candle direction',
    'averages',jsonb_build_array('SMA9','SMA20','SMA44','EMA99','SMA200'),
    'vcpr_role','Confluence and blocker/target context; VCPR touch alone is not a trade',
    'minimum_score',8,
    'risk','Paper only: recent M5 swing plus ATR buffer; T1=1R, T2=2R'
  ),
  jsonb_build_object(
    'status','INITIAL SIGNAL TEST',
    'warning','Rules are newly frozen for testing and have not demonstrated an out-of-sample trading edge.'
  )
)
on conflict (strategy_id) do update set
  name=excluded.name,
  strategy_group=excluded.strategy_group,
  timeframe=excluded.timeframe,
  status=excluded.status,
  mode=excluded.mode,
  enabled=excluded.enabled,
  dashboard_visible=excluded.dashboard_visible,
  telegram_enabled=excluded.telegram_enabled,
  description=excluded.description,
  rules=excluded.rules,
  evidence=excluded.evidence,
  updated_at=now();

do $$
begin
  alter publication supabase_realtime add table public.strategy_signals;
exception when duplicate_object then null;
end $$;
